package app.eodin.deeplink

/**
 * Build configuration for the SDK.
 * This will be generated by Gradle in actual builds.
 */
internal object BuildConfig {
    const val DEBUG = true
    const val LIBRARY_PACKAGE_NAME = "app.eodin.deeplink"
    const val BUILD_TYPE = "debug"
}
